//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:21:34 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    public partial class Sys_GoodsPropertyOption_Rela    
    {    
        //Id
         public Int32 Id { get; set; }
         //属性值
         public Int32? PropertyValue { get; set; }
         //属性Id
         public Int32? PropertyId { get; set; }
         //商品Id
         public Int32? GoodsId { get; set; }
         //属性编码
         public String PropertyCode { get; set; }
    } 
}
