//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 15:02:43 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_EnterpriseOrgazation_Rela    
    {    
        //int
         public Int32 Id { get; set; }
         //组织机构Id
         public Int32? OrgazationId { get; set; }
         //企业Id
         public Int32? EnterpriseId { get; set; }
    } 
}
