//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 15:02:43 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_OrderItem_Rela    
    {    
        //
         public Int32 Id { get; set; }
         //
         public Int32 orderId { get; set; }
         //
         public Int32 GoodsId { get; set; }
         //
         public Decimal? Amount { get; set; }
         //
         public Decimal? OriginalPrice { get; set; }
         //
         public Decimal? DisPrice { get; set; }
         //
         public Decimal? RealPrice { get; set; }
         //
         public Decimal? OriginalPriceTotal { get; set; }
         //
         public Decimal? DisPriceTotal { get; set; }
         //
         public Decimal? RealPriceTotal { get; set; }
    } 
}
