//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 09:54:29 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    /// <summary>
    /// 实体-Sys_Order 
    /// </summary>
    public partial class Sys_Order    
    {    
        //Id
          public Int32 Id { get; set; }
          //OrderCode
          public String OrderCode { get; set; }
          //OrderConactPerson
          public String OrderConactPerson { get; set; }
          //OrderContactTel
          public String OrderContactTel { get; set; }
          //OrderAddress
          public String OrderAddress { get; set; }
          //CreateTime
          public DateTime? CreateTime { get; set; }
          //OrderTotalMoney
          public Decimal? OrderTotalMoney { get; set; }
          //UserCode
          public Int32? UserCode { get; set; }
          //OrderDisCountMoney
          public Decimal? OrderDisCountMoney { get; set; }
          //CardId
          public String CardId { get; set; }
          //OrderRealMoney
          public Decimal? OrderRealMoney { get; set; }
          //OrderTrans
          public String OrderTrans { get; set; }
          //OrderStatus
          public Int32? OrderStatus { get; set; }
          //OrderPayType
          public Int32? OrderPayType { get; set; }
    } 
}
