//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 09:54:29 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    /// <summary>
    /// 实体-Sys_Employee 
    /// </summary>
    public partial class Sys_Employee    
    {    
        //EmpId
          public Int32 EmpId { get; set; }
          //EmpName
          public String EmpName { get; set; }
          //EmpSex
          public Int32? EmpSex { get; set; }
          //EmpAddress
          public String EmpAddress { get; set; }
          //EmpLoginName
          public String EmpLoginName { get; set; }
          //EmpLoginPassWord
          public String EmpLoginPassWord { get; set; }
          //EmpStatus
          public Int32? EmpStatus { get; set; }
          //EmpCode
          public String EmpCode { get; set; }
          //EmpTel
          public String EmpTel { get; set; }
          //EmpTitle
          public Int32? EmpTitle { get; set; }
          //AssociatedAccount
          public Int32? AssociatedAccount { get; set; }
    } 
}
