//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:21:34 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    public partial class Sys_EnterpriseSystemUser    
    {    
        //
         public Int32 Column_15 { get; set; }
         //登录名
         public String UserCode { get; set; }
         //密码
         public String PassWord { get; set; }
         //创建时间
         public DateTime? CreateTime { get; set; }
         //上次登录时间
         public DateTime? LastLoginTime { get; set; }
         //上次登录Ip地址
         public String LastLoginIp { get; set; }
         //联系人
         public String ContactPerson { get; set; }
         //联系电话
         public String ContactTel { get; set; }
         //注册状态
         public String Status { get; set; }
    } 
}
