//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:47:13 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_GoodsSku    
    {    
        //
         public Int32 Id { get; set; }
         //sku编码:(属性1：属性2：属性3)(值1：值2：值3)
         public String SkuCode { get; set; }
         //
         public Int32 GoodsId { get; set; }
         //
         public Decimal Amount { get; set; }
    } 
}
