//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 15:02:43 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_Orgazation    
    {    
        //主键
         public Int32 DepId { get; set; }
         //组织机构名称
         public String DepName { get; set; }
         //组织机构代码
         public String DepCode { get; set; }
         //父级机构
         public Int32? DepParentId { get; set; }
         //状态
         public Int32? Status { get; set; }
         //是否商户
         public Int32? IsMerchant { get; set; }
         //组织结构类型
         public Int32? DepType { get; set; }
    } 
}
