//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:21:34 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    public partial class Sys_ConsumerScore    
    {    
        //Id
         public Int32 Id { get; set; }
         //订单Id
         public String OrderId { get; set; }
         //获得积分
         public Decimal? Score { get; set; }
         //获得时间
         public DateTime? CreateTime { get; set; }
         //
         public Int32 ConsumerId { get; set; }
         //
         public Int32? OrgazationId { get; set; }
    } 
}
