//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:21:34 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    public partial class Sys_Consumer    
    {    
        //主键
         public Int32 Id { get; set; }
         //用户名
         public String LoginCode { get; set; }
         //密码
         public String PassWord { get; set; }
         //用户状态：已认证、未认证、
         public Int32? Status { get; set; }
         //身份证
         public String CardId { get; set; }
         //积分值
         public Decimal? Score { get; set; }
         //创建时间
         public String CreateTime { get; set; }
         //联系方式
         public String Tel { get; set; }
         //联系地址
         public String Address { get; set; }
         //紧急联系人
         public String ContactPerson { get; set; }
         //紧急联系电话
         public String ContactTel { get; set; }
    } 
}
