//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:47:13 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_Employee    
    {    
        //主键
         public Int32 EmpId { get; set; }
         //姓名
         public String EmpName { get; set; }
         //性别
         public Int32? EmpSex { get; set; }
         //地址
         public String EmpAddress { get; set; }
         //登录名称
         public String EmpLoginName { get; set; }
         //密码
         public String EmpLoginPassWord { get; set; }
         //是否可用
         public Int32? EmpStatus { get; set; }
         //工号
         public String EmpCode { get; set; }
         //联系方式
         public String EmpTel { get; set; }
         //职称
         public Int32? EmpTitle { get; set; }
         //关联账户
         public Int32? AssociatedAccount { get; set; }
    } 
}
