//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 09:54:29 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    /// <summary>
    /// 实体-Sys_ConsumerActive 
    /// </summary>
    public partial class Sys_ConsumerActive    
    {    
        //Id
          public Int32 Id { get; set; }
          //Title
          public String Title { get; set; }
          //StartTime
          public DateTime StartTime { get; set; }
          //EndTime
          public DateTime EndTime { get; set; }
          //Content
          public String Content { get; set; }
          //Url
          public String Url { get; set; }
          //OrgazationId
          public Int32? OrgazationId { get; set; }
          //CreateUserId
          public Int32? CreateUserId { get; set; }
          //CreateTime
          public DateTime? CreateTime { get; set; }
          //CheckUserId
          public Int32? CheckUserId { get; set; }
          //CheckTime
          public DateTime? CheckTime { get; set; }
          //Status
          public Int32? Status { get; set; }
    } 
}
