//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:21:34 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    public partial class Sys_QrCode    
    {    
        //
         public Int32 Id { get; set; }
         //名称
         public String Name { get; set; }
         //创建时间
         public DateTime? CreateTime { get; set; }
         //关联商品Id
         public Int32? GoodsId { get; set; }
         //二维码文本信息
         public String Content { get; set; }
         //二维码状态
         public Int32? Status { get; set; }
         //二维码调用服务
         public String Url { get; set; }
         //二维码校验码
         public String Sign { get; set; }
         //二维码管理员
         public Int32? EmpId { get; set; }
         //
         public Int32? QrCodeTypeId { get; set; }
    } 
}
