//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 09:54:29 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    /// <summary>
    /// 实体-Sys_OrderItem_Rela 
    /// </summary>
    public partial class Sys_OrderItem_Rela    
    {    
        //Id
          public Int32 Id { get; set; }
          //orderId
          public Int32 orderId { get; set; }
          //GoodsId
          public Int32 GoodsId { get; set; }
          //Amount
          public Decimal? Amount { get; set; }
          //OriginalPrice
          public Decimal? OriginalPrice { get; set; }
          //DisPrice
          public Decimal? DisPrice { get; set; }
          //RealPrice
          public Decimal? RealPrice { get; set; }
          //OriginalPriceTotal
          public Decimal? OriginalPriceTotal { get; set; }
          //DisPriceTotal
          public Decimal? DisPriceTotal { get; set; }
          //RealPriceTotal
          public Decimal? RealPriceTotal { get; set; }
    } 
}
