//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 09:54:29 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace My.Model
{   

    /// <summary>
    /// 实体-Sys_EnterpriseSystemUser 
    /// </summary>
    public partial class Sys_EnterpriseSystemUser    
    {    
        //Column_15
          public Int32 Column_15 { get; set; }
          //UserCode
          public String UserCode { get; set; }
          //PassWord
          public String PassWord { get; set; }
          //CreateTime
          public DateTime? CreateTime { get; set; }
          //LastLoginTime
          public DateTime? LastLoginTime { get; set; }
          //LastLoginIp
          public String LastLoginIp { get; set; }
          //ContactPerson
          public String ContactPerson { get; set; }
          //ContactTel
          public String ContactTel { get; set; }
          //Status
          public String Status { get; set; }
    } 
}
