//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-10-27 10:47:13 by吴培德
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Model
{   

    public partial class Sys_ConsumerActive    
    {    
        //
         public Int32 Id { get; set; }
         //
         public String Title { get; set; }
         //
         public DateTime StartTime { get; set; }
         //
         public DateTime EndTime { get; set; }
         //
         public String Content { get; set; }
         //
         public String Url { get; set; }
         //
         public Int32? OrgazationId { get; set; }
         //
         public Int32? CreateUserId { get; set; }
         //
         public DateTime? CreateTime { get; set; }
         //
         public Int32? CheckUserId { get; set; }
         //
         public DateTime? CheckTime { get; set; }
         //
         public Int32? Status { get; set; }
    } 
}
